### ISSUE TITLE
Accessing clearSignature() Function

### ISSUE THREAD

**Issue by cliftonlabrum** [yuppielabel/YPDrawSignatureView#1]
First off, thank you for this. It's really handy and I appreciate that it's in Swift. :)

I have added your `YPDrawSignatureView` class to my signature view controller, and assigned the `YPDrawSignatureView` class to a `UIView` and I can sign with my finger.

The issue I'm having, however, is accessing your `clearSignature()` function from an `IBAction` in my view controller:

```
class SignatureVC: UIViewController {
 @IBAction func tapClear(sender: AnyObject) {
    YPDrawSignatureView().clearSignature()
  }
}

class YPDrawSignatureView: UIView {
  required init(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    //...
  }

  func clearSignature() {
    self.path.removeAllPoints()
    self.setNeedsDisplay()
  }
}
```

I'm getting the error `Missing argument for parameter 'coder' in call` on my function invocation:
![image](https://cloud.githubusercontent.com/assets/2513753/7458935/4dd75532-f24d-11e4-804d-3deceddfd669.png)

Any ideas? Thanks.

**Comment by cliftonlabrum** [comment]
I figured this out. I wasn't subclassing `YPDrawSignature` correctly:

```
class SignatureVC: UIViewController {
  @IBOutlet var signArea: YPDrawSignatureView!
}
```

...and then I can call `clearSignature()` from within my view controller like this:

```
@IBAction func tapClear(sender: AnyObject) {
  signArea.clearSignature()
}
```

**Comment by GJNilsen** [comment]
Did not read your issue before now because the time difference. If you are stuck on something, dont hesitate to contact me again. :-)

**Comment by cliftonlabrum** [comment]
Great, thank you! :+1:
