### ISSUE TITLE
Delegate Property?

### ISSUE THREAD

**Issue by pentarex** [yuppielabel/YPDrawSignatureView#11]
Hi I am new to ios development, but how it seems that I cant access the delegate property, Ive added one on my own... is this ok or I am doing something wrong. I am adding the YPDrawSignatureView in a table cell.

**Comment by GJNilsen** [comment]
Have you done the same as shown in the example in either the example project or the readme? Try that, and if you still are stuck, post a question on [StackOverflow](http://stackoverflow.com/search?q=YPDrawSignatureView). Its important you also post the code you have problems with. The issue tracker here at GitHub is only for reporting bugs or ask for features, not for support or help related stuff.

**Comment by pentarex** [comment]
I think I have fixed it (imho) 
https://github.com/pentarex/YPDrawSignatureView/blob/master/source/YPDrawSignatureView.swift

Check the stuff with //ADDED Comments
It is working in my case. Thanks for the implementation of this tool 👍 

Edit: I am sorry for posting the question. I thought with the update something messed up thats why I have asked. Maybe you forgot something or dunno. It wasn't support related question. Sorry if it came like that :)

**Comment by GJNilsen** [comment]
Hi! I really misunderstood the issue, because I had added the delegate stuff earlier, but somehow messed up the code again without noticing it. Thats why I totally misunderstood what you wrote. I got another issue regarding this today, and compared it with my local copy, and then I got the error, lol. So thanks for your message, I really appreciate it, and I learned to be a bit more humble and read at least twice before dismissing an issue. Thank you a lot! 👍

**Comment by pentarex** [comment]
No worries mate :)

On Thursday, 28 April 2016, GJ Nilsen notifications@github.com wrote:

> Hi! I really misunderstood the issue, because I had added the delegate
> stuff earlier, but somehow messed up the code again without noticing it.
> Thats why I totally misunderstood what you wrote. I got another issue
> regarding this today, and compared it with my local copy, and then I got
> the error, lol. So thanks for your message, I really appreciate it, and I
> learned to be a bit more humble and read at least twice before dismissing
> an issue. Thank you a lot! 👍
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/yuppielabel/YPDrawSignatureView/issues/11#issuecomment-215508716

## 

Sent from Gmail Mobile

**Comment by GJNilsen** [comment]
👍
