### ISSUE TITLE
'YPDrawSignatureView' has no member 'delegate'

### ISSUE THREAD

**Issue by JeffESchmitz** [yuppielabel/YPDrawSignatureView#12]
The SignatureTest project doesn't compile.

SignatureTest - ViewController.swift, line 20: Error:(20, 5) value of type 'YPDrawSignatureView' has no member 'delegate'.

Doesn't YPDrawSignatureView need to expose a delegate? 

Did something change (refactor) with YPDrawSignatureViewDelegate recently? 

Jeff

**Comment by GJNilsen** [comment]
I messed up a paste, thanks for telling me! 👍 

Issue resolved and closed.

**Comment by JeffESchmitz** [comment]
Thanks! Looking forward to using this in an app I'm working on.
