### ISSUE TITLE
Interaction in a Scrollview

### ISSUE THREAD

**Issue by jordanHochstetler** [yuppielabel/YPDrawSignatureView#20]
We have the YPDrawSignatureView inside a scrollview and when you swipe in a vertical motion the scrollview is intercepting the input and scrolling the view instead of the YPDrawSignatureView getting the input. Does anyone know how to give this view priority?

**Comment by GJNilsen** [comment]
A while ago this same question and an answer was posted on [StackOverflow](http://stackoverflow.com/questions/35833770/ypdrawsignatureview-table-scrolling-when-drawing-signature).
I try to separate bugs and feature request from support, so support related stuff should be posted on [StackOverflow](http://stackoverflow.com/search?q=YPDrawSignatureView). You would also get a lot of answers faster in there than on github.

I pasted the same answer I gave on SO here:

> I would solve this with a button covering the cell, and when the user taps it, the cell displays the YPDrawSignatureView. Just before the signature view is shown, disable the scrolling:
> `tableView.scrollEnabled = false`
> Later when you save the signature, enable scrolling again by setting `tableView.scrollEnabled = true`.

**Comment by hadwanihardik** [comment]
I resolved this issue. Here is the solution.

 -- Redacted, see https://stackoverflow.com/questions/35833770/ypdrawsignatureview-table-scrolling-when-drawing-signature/35940220?noredirect=1#comment88433741_35940220

**Comment by GJNilsen** [comment]
The issue tracker is for bugs only, not support. Use StackOverflow for code samples.

**Comment by hadwanihardik** [comment]
I just pasted solution link not code snipet

**Comment by NikhilGangurde** [comment]
This solution doesn't work in the case of UIScrollView.

**Comment by GJNilsen** [comment]
You can still disable and enable scrolling in UIScrollViews with the delegate methods, just as with an UITableView.
`yourScrollView.isScrollEnabled = false`
If you still have a problem, ask on StackOverflow, and I'll give you an example there on how to solve it. The issue tracker here is for bugs and issues, not support.
