### ISSUE TITLE
Integrate YPDrawSignatureView in a objective-c project

### ISSUE THREAD

**Issue by lorenzoPrimi** [yuppielabel/YPDrawSignatureView#23]
Can you tell me the steps to integrate this class into an objective-c project?
Especially how to call swift methods from obj-c class.
Would be great to add it in the README
Thanks

**Comment by GJNilsen** [comment]
Since this is not a bug report or a feature request, please repeat the question on [http://stackoverflow.com/search?q=ypdrawsignatureview](Stackoverflow)
