### ISSUE TITLE
Starts drawing only after 5mm into the stroke

### ISSUE THREAD

**Issue by TyrantFox** [yuppielabel/YPDrawSignatureView#3]
Once your drawing your signature it tracks the movement of your finger nicely. It also accepts the tap well. However there is a lag between when you start moving your finger and when the gesture recognizer detects it as a pan gesture.

**Comment by GJNilsen** [comment]
Thanks for fixing it! :)

**Comment by TyrantFox** [comment]
You’re welcome - thanks for doing all the rest…

On Dec 15, 2015, at 4:19 PM, GJ Nilsen <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for fixing it! :)
