### ISSUE TITLE
Tap for dot not working

### ISSUE THREAD

**Issue by danhixon** [yuppielabel/YPDrawSignatureView#32]
Thank you for this excellent tool, I can't seem to get the dot in my signature to show up. Is there a setting to enable this or am I missing something?

**Comment by danhixon** [comment]
It seems that touchesMoved is fired on a tap and the ctr becomes 1 or 2 and the dot is not drawn. Is this happening to others?

**Comment by GJNilsen** [comment]
...

**Comment by danhixon** [comment]
I understand and thanks for taking a look. I might be able to fix it. Do you have an idea of how you'd approach it? I'm not very familiar with the view touches methods. Do you think adding a tap gesture recognizer would be appropriate?

**Comment by GJNilsen** [comment]
If we add a gesture recognizer to it, it will interfere with the existing methods. I guess the quick and dirty solution is to compare the location of the first touch in touchesBegan as well as touchesEnded. If they are identical, its a dot. Else its a line. So then I guess there has to be drawn a pre-defined dot in the location.

**Comment by GJNilsen** [comment]
I fixed it, it was just a single line that needed editing. I did a quick test on a device and in the simulator, and it looks OK. You could give it a try, and if you dont find any issues, Ill merge the branches.

**Comment by GJNilsen** [comment]
Did some more testing, works OK. Issue closed.

**Comment by danhixon** [comment]
Thank you very much! You rock!

**Comment by GJNilsen** [comment]
No problem, thanks for pointing it out 👍
