### ISSUE TITLE
Stroke colour not following through to saved image

### ISSUE THREAD

**Issue by bunkerbilly** [yuppielabel/YPDrawSignatureView#35]
Swift 3
IOS 9.0

When i change the stroke colour (e.g. red), drawing the signature the strokes are red but when i save the image it sets it back to black? any idea what could be causing this?

        let jpgImageData = UIImageJPEGRepresentation(vewSignature.getSignature()!, 0.5)
        
        do
        {
            try! jpgImageData!.write(to: URL(fileURLWithPath: "Sig.jpg"), options: [.atomic])
        }
        catch let err as NSError {
            print(err)
        }

**Comment by GJNilsen** [comment]
There is absolutely nothing wrong with your code, there is a bug in the class. Ill get back to you. Thanks for bringing this to my attention.

**Comment by GJNilsen** [comment]
And then it was fixed.
