### ISSUE TITLE
Non-'@objc' method 'didFinish()' does not satisfy requirement of '@objc' protocol 'YPSignatureDelegate'

### ISSUE THREAD

**Issue by srikumaran** [yuppielabel/YPDrawSignatureView#39]
Simply YPDrawSignatureView File Integrate with my Project, i get this issue...!
Thanks in Advance.
Waiting For your Reply.

Non-'@objc' method 'didFinish()' does not satisfy requirement of '@objc' protocol 'YPSignatureDelegate'
![screen shot 2017-06-19 at 5 15 07 pm](https://user-images.githubusercontent.com/5928263/27283678-fc40e438-5512-11e7-881e-24da1a95cc52.png)

**Comment by GJNilsen** [comment]
I cloned a fresh copy from GitHub, and I get no errors. The only stable branch is the Master branch. I do not know what you did to to get that error, and I do not have time to provide support. The only suggestion I have is to get yourself a fresh copy of the class, and follow the instructions provided.

All support questions should be posted on StackOverflow. The issue tracker is for bugs only.
