### ISSUE TITLE
CGPath, Annotation, and PDFKit iOS 11

### ISSUE THREAD

**Issue by riverbaymark** [yuppielabel/YPDrawSignatureView#45]
Not sure if this is the best place to bring this up, but I think it is something that could be useful for many developers to add signature annotations to their PDFs.  I apologize for my poor comprehension of CoreGraphics to this point as I have struggled with learning more about the  library over the weekend.

Apple does not have any documentation on their PDFKit signature widget, but has an excellent app example of using text annotation fields etc.  where it is easy to expand to push results to those fields.  That being said, it is hard to know what the signature widget actually wants to populate a PDF.  I have found a work around that was recommended on StackOverflow (https://stackoverflow.com/questions/46418871/create-pdf-annotations-using-pdfkit-ios-11) that uses CGPaths to annotate the pdf like so (and I assume the signature widget will want this as well):

let rect = CGRect(x: 250.0, y: 100.0, width: 200.0, height: 50.0)
            let annotation = PDFAnnotation(bounds: rect, forType: .ink, withProperties: nil)
            annotation.backgroundColor = .black
            
            let pathRect = CGRect(x: 0.0, y: 0.0, width: 100.0, height: 100.0)
            let path = UIBezierPath(rect: pathRect)

Easy to use this to draw a box on the PDF near the bottom middle of the PDF.  I assume if I used this instead in the last 2 lines of the code:

let sigCGPath =  CGPath
let path = UIBezierPath(cgPath: sigCGPath)

I could add it to the annotation instead of the box.  My question is how do I get the CGPath for the signature I just created in YPDrawSignatureView?  

Hope this makes sense and thanks ahead of time.

Mark

**Comment by GJNilsen** [comment]
The quick and dirty fix would be to do some small changes to the source code.
fileprivate var path = UIBezierPath() should be changed to public, and then accessing its cgpath. Im going to investigate it more closely and see if there is a way of integrating it more with PDFKit.

**Comment by riverbaymark** [comment]
Thanks @GJNilsen!

**Comment by Chris-BMA** [comment]
This indeed works after making the path property public.  To add it to a page using PDFKit, you would just create a PDFAnnotation using the "ink" subtype widget.

```
let annotation = PDFAnnotation(bounds: someRect, forType: .ink, withProperties: nil)
annotation.add(theBezierPath)
```

Depending upon the path's bounds, you may need to scale it **before** adding it to the annotation.  For example, I had to shrink the path after capture by quite a bit to fit it in on a corresponding line/box on a pdf form we use.

`theBezierPath.apply(CGAffineTransform(scaleX: 0.13, y: 0.13))`

**Comment by GJNilsen** [comment]
For adding an annotation that would work, but what if you want to add it so it is a part of the page itself? Annotations are just blobs of meta data, and not an integral part of the document.

**Comment by Chris-BMA** [comment]
It depends on the situation.  We have a pdf form that already exists that we bundle with the app, and we just need to populate and sign it.  Annotations work fine for that.  But if you didn't have the pdf file and you wanted to create it inside the app, you could create a UIView and lay it out accordingly, to include a subview of YSDrawSignatureView.  When the user finishes signing, you can render the whole view as PDF using Core Graphics and UIGraphicsBeginPDFContextToData().

**Comment by GJNilsen** [comment]
Ok. Well, thanks for the info, Im archiving this so the next one who needs a signature in a pdf document can find some help here.
