### ISSUE TITLE
How to load saved signature.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [yuppielabel/YPDrawSignatureView#46]
Hi,
   How can I load the signature if gets saved in to database in Data format. Can you please have a look.

**Comment by GJNilsen** [comment]
Loading signatures is not within the scope of this class, so it will not be supported. If you want an example on how to make an UIImage from NSData, please search Stackoverflow, and if there is no answer regarding that, post a question yourself. Ill check there within a day or two to give an answer if not one is given.
TheGitHub issue tracker is for bugs, not for support.
