### ISSUE TITLE
YPSignatureDelegate not public

### ISSUE THREAD

**Issue by zaggo** [yuppielabel/YPDrawSignatureView#47]
Hi,
the declaration of `protocol YPSignatureDelegate` and the `weak var delegate: YPSignatureDelegate?` property aren't declared public.
Thus (at least when `YPDrawSignature` is imported via Cocoapods), neither the delegate property nor the protocol declaration are accessible.

Both should be declared public (as the `class YPDrawSignatureView` itself)

**Comment by GJNilsen** [comment]
Ok, thanks for pointing it out. I do not use cocoapods, Im not a fan of any automation of injecting code on build time, since it can be the root of a bag of hurt when there are compatibility issues or bugs. But Ill fix it on the next update. Its coming some time next week.

**Comment by GJNilsen** [comment]
Next week is still some time in the future, sorry for that.. I have asked one of the fork owners who has fixed this to make a pull request so I can merge in the changes. This is for proper accreditation.

If no pull request has been made within the next couple of days, Ill do it myself.

**Comment by caesss** [comment]
Any updates on the solution here? I'm on xcode 9 swift 4 imported this into my project, works great but I can't get the delegates to trigger. Any suggestions?
UPDATE: 
Nevermind, I forgot to set the delegate 
signatureView.delegate = self

**Comment by bluelinecoding** [comment]
Possible to add new version to Cocoapods?

**Comment by GJNilsen** [comment]
To make a cocoapod, I need to install a lot of crap, like Ruby and, ofcourse, cocoapod itself. I never use dependency managers, and do not want to install them either. There was one who did set up cocoapods for this class, but he included too much stuff in it, so it was not a clean cocoapod. But if there is someone out there who could set up a cocoapod for this class, please do, but t only include the source file in the sources folder, and not the demo project.
