### ISSUE TITLE
How to get imageurl

### ISSUE THREAD

**Issue by bisht2ankit** [yuppielabel/YPDrawSignatureView#48]
How to get  signature image url?

**Comment by GJNilsen** [comment]
There is no image url. The image is stored in a class property itself, from there you can do with the image whatever you like. 

`getSignature()`
- Returns signature with bounds of YPDrawSignatureView instance

`getCroppedSignature()`
- Returns signature with bounds of signature

`getPDFSignature()`
- Returns signature as Vector Path PDF Data Format
