### ISSUE TITLE
Black screen flickering on tapping the edge of the view and unable to draw towards the edge as well

### ISSUE THREAD

**Issue by iamsanketray123** [yuppielabel/YPDrawSignatureView#51]
I have a uiview which inherits from YPDrawSignatureView. But when I try to draw a signature towards the edge, the signature is not registered and sometimes the app flickers with a black screen. Although I am able to draw in the middle of the view.  I also get this error message while setting up the custom class to "YPDrawSignatureView" --> Designables - Build Failed and I am using xibs and not storyboard

**Comment by GJNilsen** [comment]
Im curious why you closed the issue. Did the problem relate to your project, or the signature class? I tried to sign on the edge of the view, and did not get the same outcome as you. Please provide more info if this is a problem related to the class.

**Comment by iamsanketray123** [comment]
The problem was in my project and not in the SignatureView. Sorry about that :(

**Comment by GJNilsen** [comment]
No problem, thanks for clarifying.
