### ISSUE TITLE
Warning : memory leak

### ISSUE THREAD

**Issue by shkar62** [yuppielabel/YPDrawSignatureView#52]
As soon as I try to draw on the view, I get memory leak warning and the app crashes. Can someone assist?

**Comment by GJNilsen** [comment]
The demo app does not crash, so if your app crashes, you probably did not set it up properly.

If you do have a problem with the class within your project, reach out at StackOverflow.

**Comment by mreilly4** [comment]
@shkar62 did you ever find out what the issue is?  As soon as I try and draw my app freezes up and begins leaking memory until it crashes.

Thanks!

**Comment by saormart** [comment]
@shkar62 and @shkar62, I'm using this great signature framework and it's working fine for me !
My app have several screens that use not only one field to sign, but two  and I did a memory leak tests and have no problem !
As @GJNilsen said, you may have miss-configured your app... Try doing some tests with it's demo to try replicate your issue!
