### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by robert-cronin** [yuppielabel/YPDrawSignatureView#53]
Any chance of getting this as a pod?

**Comment by GJNilsen** [comment]
No, not made by me, but if anyone wants to fix support for it, Ill merge it.

**Comment by oleghnidets** [comment]
Hi guys, 
Please check my PR #54. All you need is to publish the library. 
`pod repo push YPDrawSignatureView.podspec`

Looking forward to get it via CocoaPods :)

https://guides.cocoapods.org/making/making-a-cocoapod.html


Or just merge it and I will try to push library to CocoaPods.

**Comment by oleghnidets** [comment]
Unfortunately, I got an error 

> You (oleg.oleksan@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are neilliga@gmail.com.

**Comment by GJNilsen** [comment]
I merged it, so now you can push it to cocoapods..
