### ISSUE TITLE
Issue signature in UItableViewCell.

### ISSUE THREAD

**Issue by Ans67** [yuppielabel/YPDrawSignatureView#55]
I use Signature vIew in my UITableviewcell Uiview.signature not working properly.
Here is my code
@IBOutlet weak var viewSignature: YPDrawSignatureView!
 override func awakeFromNib() {
        super.awakeFromNib()
        viewSignature.delegate = self
    }

func didStart() {
        print("start")
    }

    func didFinish() {
        signatureImage = viewSignature.getSignature()!
        delegate?.signature(image: signatureImage)
    }

**Comment by saormart** [comment]
What's the problem you're facing ?
What exactly you're trying to accomplish ?

**Comment by Ans67** [comment]
I want to accomplish signature in UIview.
UIVIEW is embedded in UITableViewCell.
Currently singature can't be done properly(as per demo app it's working properly). I want to do as per demo in my current UIVIEW which is embedded in UITableViewCell.

**Comment by saormart** [comment]
So, you may remove the 2 lines from func didFinish() and if you want to capture that signature and assign it to a object you may create another function called from a button or anywhere else!
That didFinish() function is fired everytime the user "finish" the signature... if the user "touch" multiple times to sign, it will fire that function multiple times as well, that's may is the reason you have problems with it !
As you can see in the template, you may add a button like this:
`// Function for saving signature
    @IBAction func saveSignature(_ sender: UIButton) {
        // Getting the Signature Image from self.drawSignatureView using the method getSignature().
        if let signatureImage = self.signatureView.getSignature(scale: 10) {
            
            // Saving signatureImage from the line above to the Photo Roll.
            // The first time you do this, the app asks for access to your pictures.
            UIImageWriteToSavedPhotosAlbum(signatureImage, nil, nil, nil)
            
            // Since the Signature is now saved to the Photo Roll, the View can be cleared anyway.
            self.signatureView.clear()
        }
    }`

**Comment by GJNilsen** [comment]
Great answer.


## Support and Issues
GitHub Issues are for filing bug reports and feature requests only. Use [StackOverflow](http://stackoverflow.com/search?q=YPDrawSignatureView) for support related questions and help.
