### ISSUE TITLE
Add signature view to tableview.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [yuppielabel/YPDrawSignatureView#58]
Hi, 
How can I use the signature view inside a tableviewcell. As when I save the signature view after drawing ended in a local object and then again load the local object of the signature to the view(signature) while scrolling the table view. But it shows nothing on the table view. So can you please help me to achieve this.

Help would be highly appreciated.

**Comment by GJNilsen** [comment]
This has been answered here and on Stackoverflow. Please go there for support. And search before you ask!

**Comment by ambujshukla-cdn** [comment]
Hi, where it is answered?. I'm not seeing any link of stackoverflow.

**Comment by GJNilsen** [comment]
The link is in the readme file.
