### ISSUE TITLE
Set image as signature

### ISSUE THREAD

**Issue by LinusGeffarth** [yuppielabel/YPDrawSignatureView#62]
In my app, I want to save and restore the signature in a `YPDrawSignatureView`.  
Therefore, I get the drawn signature and save that as an image. When restoring, I want to set the signature to the view.
Would that be possible?

**Comment by GJNilsen** [comment]
This is not within the scope of the class, but you could set an image into the background view.

**Comment by LinusGeffarth** [comment]
When grabbing the new signature, will the imageof the restored signature be also snapshot?

**Comment by GJNilsen** [comment]
Use StackOverflow for support. GitHub Issues are for bugs only

**Comment by davidseek** [comment]
i think it's actually a pretty legit question and totally something that would be answered
in the issues section of other reps.
also this is way too broad for stackoverflow.
pretty much a guarantee to remain unanswered.
but whatevs

**Comment by davidseek** [comment]
but to answer the question @LinusGeffarth : 
from my observation there is no image to signature option.
also i assume that it would quiet hard to accomplish.

the best option (and what i did) was something like the following:

you will want to have a "remove signature" button anyways.
so when you load the view (for example through a 2nd controller),
you would usually pass an optional image (or database link).

then you could do something like: 

```
if let image = image {
   let imageView = UIImageView(image: image)
   signatureView.addSubview(imageView)
}

```

And then set the constraints of the imageView to match the signatureView.
If the user then presses the reset button,
you would hide and removeFromParent... the imageView and then the user can sign again.

I think this should give you an idea how to accomplish it.

**Comment by LinusGeffarth** [comment]
@davidseek thanks for your answer. This was actually exactly the workaround that I chose. It worked fairly well, although I had to go in an manually take a snapshot of the view to get the image back, because the built-in one wasn't respecting the view hierarchy.

**Comment by GJNilsen** [comment]
> i think it's actually a pretty legit question and totally something that would be answered
> in the issues section of other reps.
> also this is way too broad for stackoverflow.
> pretty much a guarantee to remain unanswered.
> but whatevs

The issue tracker is for tracking issues, meaning bugs, as well as feature requests. This is not the place for support questions.

The reason why I'm so strongly against having support questions in the tracker is mainly that I do not have the time to answer these questions. StackOverflow is built for community support, so you are more likely to get a quick answer over there. Also, the search function is better over there.

**Comment by davidseek** [comment]
@GJNilsen I understand your point. But I'm also a 3 year active member on Stack and I have more than 1.5M views on my answers and questions and in my experience questions for specific frameworks such as yours tend to remain under the radar as most of the Users are answering core questions such as "How to resize UIView", but are not familiar with specific frameworks and it might take a couple weeks if ever to get an answer.

And here is the problem. People asking those questions are usually rookies. 
And they either move on from your framework or get frustrated and quiet the whole thing.
I'm regularly using around 30 github repos such as yours.
And I try to "give back" by being an active member of those repos.

I get it that you dont have the time to answer questions.
I barely do in my own open repos either. 
Not even claiming that I own even one that has nearly as much traction as yours.
But questions might be answered by other people such as I did on this question to the original author.
And when other people then have similar or same questions they will find it here in your board.

And if you like it or not, this is the norm on github.
Look into ANY other repo with >100 starts. 
80% of the issues are howto questions and they are commonly answered by the community.

But nevertheless. 
This is just how I feel.
This is your repo and I respect that your rules apply.
Just tried to give you feedback.

**Comment by GJNilsen** [comment]
I do understand your point of view, I really do.

The problem is when someone is looking for a library, and if there are a lot of open issues, most just assume there is a lot wrong with the library and move on. As mentioned before, support requests do clutter the space, making the important stuff, like bugs and feature requests, drown in the noise. Also for the issue tracker to do its work, issues have to stay open until solved. Since I do not have the time to support the class, and I can't rely on random users to pitch in, there would accumulate open issues. In addition, I have an OCD regarding unfinished business. If it was not for that, the issues could stay open for someone else to answer. It is not my intention to appear douchy, but I really have an issue with open issues. 🤪

**Comment by davidseek** [comment]
I completely get your OCD. I'm the same way! :-)
