### ISSUE TITLE
Lag in iPhone X

### ISSUE THREAD

**Issue by SriKrishnaCovalense** [yuppielabel/YPDrawSignatureView#63]
Greeting,

I am developing a pet project using your library for signature module. Everything works fine, but when i try to run the same in iPhone X, either in simulator or in real device, there is a lot of latency in the sense that the Touch Events Don't catch up with the Drawing on the Screen.

The same issue is not being reproduced in lower Devices.

Please check and let us know.

**Comment by GJNilsen** [comment]
Im running the sample project on my personal iPhone X with iOS 12 beta 10, and I do not experiencing any latency problem. This has to relate to your own code.
