### ISSUE TITLE
old version on Cocoapods !

### ISSUE THREAD

**Issue by X901** [yuppielabel/YPDrawSignatureView#67]
I did install it via Cocoapods 
by writing 
`pod 'YPDrawSignatureView'`

and the version is **1.1.2** not **1.2**

even when I use `pod update`

**Comment by GJNilsen** [comment]
This is because sombody else published their fork on cocoapods. I asked the person to delete it, but got no response. Also the guys managing the site do not respond.

**Comment by X901** [comment]
ok without Cocapods
I just need to move `YPDrawSignatureView.swift`
to my project ?
or they are something else like `import` ?

**Comment by GJNilsen** [comment]
You just put it somewhere in your project. No imports.
