### ISSUE TITLE
Sometimes unable to get images 

### ISSUE THREAD

**Issue by JustinJusz** [yuppielabel/YPDrawSignatureView#68]
![screenshot 2019-01-18 at 10 44 53 am](https://user-images.githubusercontent.com/44425802/51366912-32f63880-1b0e-11e9-8124-8d387d5f99d5.png)
![screenshot 2019-01-18 at 10 45 27 am](https://user-images.githubusercontent.com/44425802/51366914-32f63880-1b0e-11e9-97ac-0bcf7688c810.png)

**Comment by GJNilsen** [comment]
Please provide more info than two screenshots, and if you close the report yourself, provide the reason for closing it.
