### ISSUE TITLE
Detect handwritten signature

### ISSUE THREAD

**Issue by PawanmSpaceo** [yuppielabel/YPDrawSignatureView#69]
I want to detect the signature from Camera Capture image, is it possible?

**Comment by JustinJusz** [comment]
I think not possible. We can draw only through the views not in images

**Comment by PawanmSpaceo** [comment]
Ok @JustinJusz Thanks...

**Comment by GJNilsen** [comment]
As @justinjusz sats, this is outside of the scope of the class. It is rather an interesting idea though, and maybe something for another project.
