### ISSUE TITLE
Has Signature

### ISSUE THREAD

**Issue by abduranjum** [yuppielabel/YPDrawSignatureView#7]
How to check if the signature is present now? The method has been removed. Also the touch delegates are not intercept able in the view controller, by which I can know that something happened. P.S.: I'm bridging to Objective-C.

**Comment by GJNilsen** [comment]
Calculating the content of the produced UIImage was never the scope of this view. It is not good OOP to put some kind of validation within the display mechanism. There would also be a lot of different needs regarding a validator, some would calculate a mathematical hash as a result of the signature, and run some algorithm to compare it with previously stored signatures, others merely checking if the signature field is not blank. Thats why making a validator is not something I will do.

I would recommend you to check out similar projects made in Objective-C. [MacHeads101](https://www.youtube.com/watch?v=8KV1o9hPF5E&list=UU7fIuG6L5EPc9Ijq2_BCmIg) has a nice tutorial that inspired me to make this class.

**Comment by abduranjum** [comment]
Thanks very much for the help and for the control!!!

**Comment by yuppielabel** [comment]
For a quick and dirty validating routine, I would set up the controller where you have the view like this:

`@IBOutlet weak var drawSignatureView: YPDrawSignatureView!

@IBAction func save(sender: AnyObject) {
        let img = drawSignatureView.getSignature()
        let imgData: NSData = UIImageJPEGRepresentation(img, 0)!
        print("Size of Image: \(imgData.length) bytes")
    }`
Use the size in bytes you get for your signature image when its empty, and do an if-else on the returned size, if someone has signed, the size in bytes will be larger than the empty signature image.

**Comment by GJNilsen** [comment]
You got your wish granted!

Before getting the UIImage from the signature view, check if its new calculated property `containsSignature` is true.

Usage:

```
@IBOutlet weak var drawSignatureView: YPDrawSignatureView!

@IBAction func save(sender: AnyObject) {
    if drawSignatureView.containsSignature {
        let img = drawSignatureView.getSignature()
        // Do something with img
    } else {
        // Alert the user or do something else
    }
}
```

**Comment by abduranjum** [comment]
Thanks!

**Comment by GJNilsen** [comment]
Just remember to download the latest source file :+1:

**Comment by abduranjum** [comment]
Done! :)
