### ISSUE TITLE
Delegate property and YPSignatureDelegate are not public therefore not accessible to external code

### ISSUE THREAD

**Issue by fvolchyoksm** [yuppielabel/YPDrawSignatureView#75]
**Describe the bug**
YPDrawSignatureView's `weak var delegate` property and corresponding `protocol YPSignatureDelegate` are not public and could not be accessed/implemented if installed via CocoaPods.

**To Reproduce**
1. Install via cocoapods `pod 'YPDrawSignatureView'`
2. Do everything according to readme including settings class for UIView, import YPDrawSignatureView etc. 
3. Try to implement delegate, access delegate property

**Expected behavior**
Both delegate property and protocol are accessible and seen by compiler

**Screenshots**
![image](https://user-images.githubusercontent.com/52209161/66550829-e4327800-eb4e-11e9-89d7-9fc607feeaad.png)
![image](https://user-images.githubusercontent.com/52209161/66550854-ee547680-eb4e-11e9-86c7-3e618d97be0b.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

**Smartphone (please complete the following information):**
 - not applicable

**Additional context**
I'm using Swift 4 in my projects by highly doubt it's the cause. Now matter what mentioned entities just should be public and that should resolve the issue.

**Comment by GJNilsen** [comment]
There is no support for cocoa pods. The problem is solved whe  you add the class as instructed in the readme.
