### ISSUE TITLE
Non-'@objc' method 'didFinish' does not satisfy requirement of '@objc' protocol 'YPSignatureDelegate'

### ISSUE THREAD

**Issue by JackTileman** [yuppielabel/YPDrawSignatureView#77]
We are using YPDrawSignature from here to draw a signature on the IOS App.

We are getting the following error on the UIViewController.

Non-'@objc' method 'didFinish' does not satisfy requirement of '@objc' protocol 'YPSignatureDelegate'

The UIViewController is this.

    class SignatureViewController:  UIViewController , UICollectionViewDelegate, UICollectionViewDataSource, YPSignatureDelegate {
    func didStart(_view : YPDrawSignatureView) {
       // print("Started Drawing")
    }

    func didFinish(_view : YPDrawSignatureView){
      // func didFinish (){
     }

    }
The YPDrawSignatureView has the following Delegate

    @objc
    public protocol YPSignatureDelegate: class {
      func didStart(_ view : YPDrawSignatureView)
      func didFinish(_ view : YPDrawSignatureView)

     }

    extension YPSignatureDelegate {

      func didStart(_ view : YPDrawSignatureView) {}
      func didFinish(_ view : YPDrawSignatureView) {}

     }

Link to [SO](https://stackoverflow.com/questions/58996442/non-objc-method-didfinish-does-not-satisfy-requirement-of-objc-protocol).

**Comment by GJNilsen** [comment]
You have a typo in your code. The protocol requires
`func didStart(_ view :`
You have
`func didStart(_view : `
And the same goes for didFinish as well.

Please read the readme file carefully before opening issues. Issues like this is the reason why you should take it on Stackoverflow.
