### ISSUE TITLE
Signature Vector svg format

### ISSUE THREAD

**Issue by ARASHz4** [yuppielabel/YPDrawSignatureView#78]
signature can be exported as svg format

**Comment by GJNilsen** [comment]
This would be really great. But support for it demands a lot of code, a svg library is probably 40 times as big as this little class, so a direct integration on svg within the class is far beyond the scope. If I had the time I could write a tutorial on how to integrate the class with one of the svg libraries, but for now Im swamped with work.

**Comment by ludivinefafournoux** [comment]
Yes It would be great !

**Comment by GJNilsen** [comment]
There are SVG libraries and functions here on GitHub, I would use one of them, and run the CGPaths obtained from the YPDrawSignatureView through it. 

Go to [TextPaths](https://github.com/malczak/TextPaths/blob/master/Samples/TextToSVG/TextToSVG/ViewController.swift) by @malczak for an example on how to convert CGPaths to SVG.

Adding any kind of export support is outside the scope of the YPDrawSignatureView. As in the name, it's only a view, not a library.
