### ISSUE TITLE
Delegate isn't public

### ISSUE THREAD

**Issue by andrei-7peakssoftware-zz** [yuppielabel/YPDrawSignatureView#80]
**Describe the bug**
Currently delegate is not marked as public and can't be used from the client code.
`weak var delegate: YPSignatureDelegate?`

**To Reproduce**
let view = YPSignatureDelegate()
view.delegate = self

**Expected behavior**
Expect to have it public to be able to use.

**Comment by GJNilsen** [comment]
The delegate has been public for a long time. 

https://github.com/GJNilsen/YPDrawSignatureView/blob/cb5465391809366c3520ddfe52ca3e4a3b0bf072/Sources/YPDrawSignatureView.swift#L30

**Comment by GJNilsen** [comment]
I can’t understand how you got that line, since it is two years since it was fixed. You should explain a bit more, @andrei-7peakssoftware

**Comment by andrei-7peakssoftware-zz** [comment]
Having pod 'YPDrawSignatureView' and doing pod update installs YPDrawSignatureView (1.1.2)
This version doesn’t have public keyword. 

By trying to specify version pod 'YPDrawSignatureView', '~> 1.1.3’ and doing pod update I get an error:

CocoaPods could not find compatible versions for pod "YPDrawSignatureView”:   
  In Podfile:     
    YPDrawSignatureView (~> 1.1.3)

**Comment by GJNilsen** [comment]
That explains it. I do not support CocoaPods,  I hate it with a vengeance. Furthermore, the CocoaPod is not maintained by me, and I do not have access to do anything with it. Now that piece of crap points to a more than two years old and buggy version of the code.

This is the reason you should **NEVER** use CocoaPods, you can't trust you get the correct code.

**Comment by andrei-7peakssoftware-zz** [comment]
As long as I don't need to use resources I agree it's better to use SPM. May be you should mention it in Readme to avoid similar issues. I believe there are many who's gonna try to use it with Cocoapods as well.
