### ISSUE TITLE
Why no Carthage or CocoaPod support

### ISSUE THREAD

**Issue by GJNilsen** [yuppielabel/YPDrawSignatureView#9]
If you build a project and depend on fetching code from elsewhere that's not under your own control, you may one day end up opening a big bag of hurt. You should always build your whole app purely from content in your own repositories. Repositories are deleted and accounts are abandoned almost every day, and small projects like this one has no guarantee to be around tomorrow. Im committed to keeping YPDrawSignatureView updated, but still that's no guarantee it will be around.

Its not being arrogant or having some beef with dependency injection, big and widely supported projects can safely be injected, but this small class will not have support for Carthage or CocoaPods within the foreseeable future. Thanks for understanding.

[Read how dependency injection can go terribly wrong](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos)

**Comment by kaishin** [comment]
As an OSS maintainer myself, I prefer to leave it up to library users to decide how to best use their time. Forking, using submodules, or copy-pasting code are all more time consuming and introduce extra overhead in general. I do not want to make this decision on behalf of others.

**Comment by GJNilsen** [comment]
You are free to do whatever you like, so am I. I do not see a future in Carthage or CocoaPods, and thats why I do not want to use time supporting it. But if someone would do the job and making a pull request, I would happily merge it.

**Comment by kaishin** [comment]
@GJNilsen Fair enough. My comment was purely to provide a different take, and I am by no mean asking you or anyone else to do anything. I will fork and open a PR if we end up using YPDrawSignatureView in my current project. Thank you for all the hard work!

**Comment by GJNilsen** [comment]
I did not mean to disrespect you, its just my personal opinion regarding dependency injection. Im a strong proponent that you only depend on code you have full control over.

I have one example. I wanted to make a tool for combining different PDF files, and provide support for DropBox. The DropBox library depends on a couple of different other libraries that also depended on other libraries. Because there is a cross-dependency to different versions of the same library, getting the project to build would take days debugging and rewriting.

Using small components, like this class, results in easy to manage code. If something is wrong, you can fix it yourself without much hassle, and without the complete project falling together like a house of cards.

By the way, its the collective contribution from the users that makes open source code great, and any improvements are higly appreciated.

**Comment by kaishin** [comment]
> Im a strong proponent that you only depend on code you have full control over.

@GJNilsen I share your point of view as a library user. I fork or rewrite stuff from scratch and only use micro-libraries like this one. On my own open-source libraries I always try to not have 3rd party dependencies to avoid the scenario your described.
